# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
import numpy as np
np.__version__
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
import numpy as np
zer=np.zeros(10)
print(zer)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
import numpy as np
n = np.zeros((7,4))
print(n.size*n.itemsize)
print("%d bytes" %(n.size * n.itemsize))


224
224 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
import numpy as np
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
import numpy as np
z=np.zeros(10)
z[5]=1
z

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
import numpy as np
z=np.arange(10,49+1)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
import numpy as np
z=np.arange(1,49+1)[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
import numpy as np
ap = np.array([0,1,2,3,4,5,6,7,8])
z=ap.reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
import numpy as np
ap = np.array([1,2,0,0,4,0])
ap[np.nonzero(ap)]

array([1, 2, 4])

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
import numpy as np
print(np.eye(3,3))     #print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [7]:
import numpy as np
ap=np.random.random((3,3,3))
ap


array([[[0.15360529, 0.36722332, 0.30354351],
        [0.12935544, 0.24414049, 0.1143482 ],
        [0.40306427, 0.03322362, 0.68935871]],

       [[0.41739974, 0.06685905, 0.4249486 ],
        [0.47931133, 0.42204325, 0.99574494],
        [0.11730383, 0.18528672, 0.28969234]],

       [[0.15790579, 0.46432079, 0.87171498],
        [0.39933962, 0.71651265, 0.56245073],
        [0.10036305, 0.68144566, 0.44019581]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
import numpy as np
ap=np.random.random((10,10))
print('minimum and maximum values are:')
print(ap.min(),ap.max())

minimum and maximum values are:
0.004449170115994772 0.9724583232283053


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
import numpy as np
ap=np.random.random(30)
print('mean value for the size of 30:')
ap.mean()

mean value for the size of 30:


0.48157843576686565

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
import numpy as np
ap = np.ones((5,5))
ap[1:-1,1:-1]=0
ap

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [4]:
import numpy as np
ap = np.ones((2,2))
arr1 = np.pad(ap, pad_width = 1, mode='constant', constant_values=0) 
arr1

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [8]:
nan
False
False
nan
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [10]:
import numpy as np
ap=np.diag([1,2,3,4])
ap


array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [29]:
import numpy as np
x=np.ones((3,3))
x=np.zeros((8,8),dtype=int)            #alteranate wise zero after one
x[1::2,::2] = 1                          
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [40]:
import numpy as np
np.unravel_index(100,[6,7,8])

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [48]:
import numpy as np
a= np.array([1,2,3,4,5,6,7,8])
np.tile(a,(8,2))

array([[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [70]:
import numpy as np
ap = np.random.random((5,5))
mini,maxi= ap.min(),ap.max()
ap = (ap-mini)/(ap-maxi)
print(ap)

[[ -0.54418774  -0.          -0.45982172  -2.17232194  -0.14645083]
 [ -3.07626311  -0.26266966  -0.16119012 -11.12168562 -32.61236067]
 [ -1.13407718  -1.83952046  -0.49025018  -4.99600037  -2.39525871]
 [ -3.54122867  -0.40158242  -0.24793839  -5.28282788  -0.45226464]
 [ -0.90415083  -0.76757106          inf  -0.81429119  -0.71157325]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [83]:
arr = np.array([1 ,2 ,3 ], dtype='f')
print(arr.dtype)

float32


In [110]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [87]:
a=np.random.random([5,3])
b=np.random.random([3,2])
np.dot(a,b)

array([[0.766002  , 0.68942373],
       [1.16376542, 0.88981505],
       [0.51399891, 0.5207407 ],
       [0.74271676, 0.65929844],
       [1.32716916, 0.95368477]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [98]:
a= np.arange(1,15)
a[(a>3) & (a<8)] *=0
print(a)

[ 1  2  3  0  0  0  0  8  9 10 11 12 13 14]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [102]:

print(sum(range(5),-1))
from numpy import *                         #'*' implies that to make code in one module available in another.
print(sum(range(5),-1))



10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [111]:
Z=np.array(10)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

10000000000
512
False
10j
10.0
False


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [113]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [134]:
Z = np.random.uniform(-10,+10,3)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[-8.  5. -8.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [126]:
ap1 = np.array([0,10,19,34,55])
ap2 = np.array([0,10,14,34])
print(np.intersect1d(ap1,ap2))

[ 0 10 34]


In [129]:
ap1 = np.random.randint(0,10,10)
ap2 = np.random.randint(0,10,10)
print(np.intersect1d(ap1,ap2))

[0 5 7 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [135]:
np.seterr(all=None, divide=None, over=None, under=None, invalid=None)

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [138]:
defaults = np.seterr(all="ignore")
Z = np.ones(1)/0

# Back to sanity
_ = np.seterr(**defaults)
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [142]:
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [144]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2022-11-11
2022-11-12
2022-11-13


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [145]:
ap = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(ap)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [151]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.negative(A,out=A)
np.multiply(A,B,out=A)
np.divide(A,2,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [152]:
ap = np.random.uniform(0,10,10)

print (ap - ap%1)
print (np.floor(ap))
print (np.ceil(ap)-1)
print (ap.astype(int))
print (np.trunc(ap))

[9. 6. 5. 1. 5. 8. 8. 9. 0. 5.]
[9. 6. 5. 1. 5. 8. 8. 9. 0. 5.]
[9. 6. 5. 1. 5. 8. 8. 9. 0. 5.]
[9 6 5 1 5 8 8 9 0 5]
[9. 6. 5. 1. 5. 8. 8. 9. 0. 5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [153]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [155]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [156]:
ap = np.linspace(0,1,12,endpoint=True)[1:-1]
print(ap)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [159]:
ap = np.array([5,4,6,9,4,2,4,1])
ap.sort()
print(ap)

[1 2 4 4 4 5 6 9]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [165]:
ap = np.arange(20)
np.add.reduce(ap)

190

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [166]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [339]:
Z = np.zeros(10)
Z.flags.writeable = False        #read only
Z[0] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [175]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.87359193 0.83067621 0.92914824 0.72246528 0.55051289 0.94422432
 0.45138912 0.57602945 1.02264275 0.99347499]
[1.13517683 0.94476287 1.52922401 1.31807356 1.05572295 0.92791844
 0.32497666 0.60608712 0.55530239 1.48116931]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [178]:
ap = np.array([5,4,6,8,5,3,7,9,3])
ap[ap.argmax()] = 0
print(ap)

[5 4 6 8 5 3 7 0 3]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [179]:
ap = np.zeros((5,5), [('x',float),('y',float)])
ap['x'], ap['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(ap)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [180]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [181]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [187]:
np.set_printoptions(threshold=2)
Z = np.ones((4,6))
print(Z)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [193]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

78


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [195]:
ap = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(ap)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ... ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [198]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.75085973 0.99805168 ... 0.19504717 0.94404117 0.54798819]
 [0.75085973 0.         0.74302133 ... 0.66911697 0.7363256  0.84563488]
 [0.99805168 0.74302133 0.         ... 1.06839228 0.06535028 0.60579562]
 ...
 [0.19504717 0.66911697 1.06839228 ... 0.         1.02181375 0.70480629]
 [0.94404117 0.7363256  0.06535028 ... 1.02181375 0.         0.54069178]
 [0.54798819 0.84563488 0.60579562 ... 0.70480629 0.54069178 0.        ]]
[[0.         0.36763805 0.22568866 ... 0.77119607 0.69396933 0.78123664]
 [0.36763805 0.         0.14687669 ... 0.48939039 0.38094179 0.48249913]
 [0.22568866 0.14687669 0.         ... 0.56953643 0.47943455 0.60829237]
 ...
 [0.77119607 0.48939039 0.56953643 ... 0.         0.12495826 0.74015417]
 [0.69396933 0.38094179 0.47943455 ... 0.12495826 0.         0.61972834]
 [0.78123664 0.48249913 0.60829237 ... 0.74015417 0.61972834 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [197]:
ap = np.arange(10, dtype=np.int32)
ap = Z.astype(np.float32, copy=False)
print(ap)

[ 0.  1.  2. ... 97. 98. 99.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [201]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [204]:
ap = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(ap):
    print(index, value)
for index in np.ndindex(ap.shape):
    print(index, ap[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [205]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 ...
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [206]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [207]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.0426184  -0.19029303 -0.21621051 ...  0.49059856 -0.0894513
   0.0414624 ]
 [ 0.32701908 -0.53255357  0.32959091 ...  0.30445621  0.2859325
   0.30999723]
 [ 0.26845205  0.34913182  0.28595732 ... -0.0986626  -0.28516568
  -0.16178392]
 [ 0.18956951 -0.02217843 -0.33359822 ... -0.47048827  0.42179093
  -0.00319235]
 [ 0.44432523 -0.24185759  0.2535512  ... -0.42560895  0.39263984
  -0.0051684 ]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [208]:
ap = np.random.randint(0,10,(3,3))
print(ap)
print(ap[ap[:,1].argsort()])

[[9 3 1]
 [0 6 3]
 [6 0 6]]
[[6 0 6]
 [9 3 1]
 [0 6 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [222]:
ap = np.random.randint(0,3,(3,10))
print((~ap.any(axis=0)).any())


True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [223]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5004943620043345


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [224]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [230]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

ap = NamedArray(np.arange(70), "range_70")
print (ap.name)

range_70


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [238]:
ap = np.ones(10)
I = np.random.randint(0,len(ap),25)
np.add.at(ap, I, 1)
print(*ap)


3.0 6.0 3.0 3.0 2.0 5.0 3.0 2.0 3.0 5.0


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [241]:
a=[7,4,6,8,4,2]
b=[3,5,8,4,2,7]
np.bincount(a,b)


array([0., 0., 7., ..., 8., 3., 4.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [243]:
w,h = 17,17
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [244]:
A = np.random.randint(0,10,(3,4,3,4))     # solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
                                          # solution by flattening the last two dimensions into one
                                          # (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[61 47 54 52]
 [51 58 63 56]
 [52 57 58 68]]
[[61 47 54 52]
 [51 58 63 56]
 [52 57 58 68]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [245]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.4916729  0.58936883 0.46943598 ... 0.58590411 0.52495487 0.67374948]
0    0.491673
1    0.589369
2    0.469436
3    0.459843
4    0.439012
5    0.603737
6    0.608237
7    0.585904
8    0.524955
9    0.673749
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [250]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(np.sum(A * B.T, axis=1))
print(np.einsum("ij,ji->i", A, B))

[1.72634421 1.34468586 1.10277808 1.53940627 1.18648711]
[1.72634421 1.34468586 1.10277808 1.53940627 1.18648711]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [251]:
ap = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(ap) + (len(ap)-1)*(nz))
Z0[::nz+1] = ap
print(Z0)

[1. 0. 0. ... 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [253]:
A = np.ones((5,5,3))
B = 7*np.ones((5,5))
print(A * B[:,:,None])

[[[7. 7. 7.]
  [7. 7. 7.]
  [7. 7. 7.]
  [7. 7. 7.]
  [7. 7. 7.]]

 [[7. 7. 7.]
  [7. 7. 7.]
  [7. 7. 7.]
  [7. 7. 7.]
  [7. 7. 7.]]

 [[7. 7. 7.]
  [7. 7. 7.]
  [7. 7. 7.]
  [7. 7. 7.]
  [7. 7. 7.]]

 [[7. 7. 7.]
  [7. 7. 7.]
  [7. 7. 7.]
  [7. 7. 7.]
  [7. 7. 7.]]

 [[7. 7. 7.]
  [7. 7. 7.]
  [7. 7. 7.]
  [7. 7. 7.]
  [7. 7. 7.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [260]:
A = np.array([[ 5 , 6 , 7 , 8 , 9],[ 0 , 1,  2 , 3 , 4],[10 ,11 ,12 ,13 ,14],[15 ,16 ,17 ,18 ,19],[20 ,21 ,22 ,23 ,24]])
print('normal before swap \n',A)
A[[0,1]] = A[[1,0]]
print(A)

normal before swap 
 [[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [263]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 6, 47) ( 6, 75) ( 6, 82) ... (67, 81) (70, 74) (82, 93)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [268]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 ... 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [269]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3. ... 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [274]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
ap = rolling(np.arange(10), 3)
print(ap)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 ...
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [278]:
ap = np.random.randint(0,2,100)
np.logical_not(ap, out=ap)

ap= np.random.uniform(-1.0,1.0,100)
np.negative(ap, out=ap)

array([ 0.10254015, -0.73919855,  0.14985606, ...,  0.08366074,
       -0.40652625,  0.58458958])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [276]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[13.63288697  8.96097331  7.8733822  ...  2.87010594  3.8692894
 14.3586478 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [277]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[2.91030991e+00 4.19103164e+00 1.33864594e+01 ... 2.11809439e+00
  6.22412363e+00 4.08790713e+00]
 [3.22965732e+00 4.54938401e+00 1.42671480e+01 ... 2.14998338e+00
  6.71216329e+00 4.89974478e+00]
 [8.97892095e+00 1.19674683e+01 2.95321223e+00 ... 1.00167645e+01
  1.10286520e+01 1.35211215e+01]
 ...
 [5.57754706e+00 2.31275749e-03 1.03933889e+01 ... 1.60193585e+00
  2.00048279e+00 5.31994636e-01]
 [9.94739735e-01 1.62908863e+00 7.50986086e+00 ... 1.69804454e+00
  2.82036696e+00 1.37499573e+00]
 [4.53794897e+00 7.32678907e+00 1.34127666e+00 ... 5.12162050e+00
  6.70028918e+00 1.09680708e+01]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [281]:
ap = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(ap,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 ...
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [287]:
ap = np.random.uniform(0,2,(17,12))
U, S, V = np.linalg.svd(ap)                       # Singular Value Decomposition
rank = np.sum(S > 1e-7)
print(rank)

12


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [290]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

7


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [291]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 1 2]
   [4 4 4]
   [0 3 0]]

  [[1 2 0]
   [4 4 4]
   [3 0 3]]

  [[2 0 4]
   [4 4 2]
   [0 3 2]]

  ...

  [[2 0 3]
   [4 1 4]
   [3 4 0]]

  [[0 3 0]
   [1 4 4]
   [4 0 3]]

  [[3 0 1]
   [4 4 2]
   [0 3 0]]]


 [[[4 4 4]
   [0 3 0]
   [2 1 0]]

  [[4 4 4]
   [3 0 3]
   [1 0 2]]

  [[4 4 2]
   [0 3 2]
   [0 2 0]]

  ...

  [[4 1 4]
   [3 4 0]
   [0 0 3]]

  [[1 4 4]
   [4 0 3]
   [0 3 0]]

  [[4 4 2]
   [0 3 0]
   [3 0 0]]]


 [[[0 3 0]
   [2 1 0]
   [0 3 3]]

  [[3 0 3]
   [1 0 2]
   [3 3 3]]

  [[0 3 2]
   [0 2 0]
   [3 3 3]]

  ...

  [[3 4 0]
   [0 0 3]
   [1 3 3]]

  [[4 0 3]
   [0 3 0]
   [3 3 2]]

  [[0 3 0]
   [3 0 0]
   [3 2 2]]]


 ...


 [[[3 4 1]
   [4 0 0]
   [1 3 3]]

  [[4 1 0]
   [0 0 3]
   [3 3 4]]

  [[1 0 0]
   [0 3 2]
   [3 4 4]]

  ...

  [[0 3 2]
   [0 3 1]
   [4 1 2]]

  [[3 2 0]
   [3 1 1]
   [1 2 2]]

  [[2 0 2]
   [1 1 2]
   [2 2 0]]]


 [[[4 0 0]
   [1 3 3]
   [1 3 2]]

  [[0 0 3]
   [3 3 4]
   [3 2 1]]

  [[0 3 2]
   [3 4 4]
   [2 1 2]]

  ...

  [[0

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [294]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 5  8 12  8  5]
 [ 8  3  8 11  9]
 [12  8  5 42 10]
 [ 8 11 42  4  5]
 [ 5  9 10  5  9]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [297]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


[[200.]
 [200.]
 [200.]
 ...
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [301]:
Z = np.ones((19,19))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16. 12.]
 [16. 16. 16. 16. 12.]
 [16. 16. 16. 16. 12.]
 [16. 16. 16. 16. 12.]
 [12. 12. 12. 12.  9.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [303]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [307]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
# Slow
print (Z[np.argsort(Z)[-n:]])
# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [308]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 ...
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [315]:
ap = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(ap.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [316]:
x = np.random.rand(int(5e7))
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

4.02 s ± 333 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
197 ms ± 1.63 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
180 ms ± 1.17 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [317]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[2 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [319]:
ap = np.random.randint(0,5,(10,3))
print(ap)
U = ap[~(ap[:,0,None]==ap[:,1:]).all(axis=1)]
print(U)

[[4 3 4]
 [0 0 4]
 [3 2 4]
 ...
 [4 4 4]
 [0 2 4]
 [1 2 3]]
[[4 3 4]
 [0 0 4]
 [3 2 4]
 ...
 [4 0 4]
 [0 2 4]
 [1 2 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [320]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [325]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [327]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.05219378, 0.42423672, 0.35913509, ..., 0.1736704 , 0.48849816,
        0.27493336],
       [0.03048506, 0.24778586, 0.20976166, ..., 0.10143645, 0.28531933,
        0.16058157],
       [0.04527983, 0.36803939, 0.31156157, ..., 0.15066481, 0.42378831,
        0.23851378],
       ...,
       [0.07756919, 0.63049081, 0.53373827, ..., 0.25810493, 0.72599467,
        0.4085996 ],
       [0.03497637, 0.28429175, 0.24066551, ..., 0.11638092, 0.32735497,
        0.18423979],
       [0.00951149, 0.07731042, 0.06544668, ..., 0.03164868, 0.08902104,
        0.05010225]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [334]:
ap1 = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*ap1*np.cos(ap1)
y = a*ap1*np.sin(ap1)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5        # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                           # integrate path
r_int = np.linspace(0, r.max(), 200)            # regular spaced path
x_int = np.interp(r_int, r, x)                  # integrate path
y_int = np.interp(r_int, r, y)
print(r_int)
print(x_int)
print(y_int)

[  0.           2.48788858   4.97577716 ... 490.11405003 492.60193861
 495.08982719]
[ 0.         -0.37313123 -2.59817608 ... 30.72807504 31.15312186
 31.39601771]
[ 0.          1.74026724  0.98181658 ... -5.42495146 -2.97607515
 -0.50007209]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [335]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [338]:
X = np.random.randn(100)                       # random 1D array
N = 50000                                       # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confidence  = np.percentile(means, [2.5, 97.5])
print(confidence )

[-0.36325867  0.02027129]
